"""
youtube_session.py -- keeps a real, browser-refreshed YouTube login session
alive automatically, replacing the manual "export cookies from a browser
extension" step that has twice been the actual root cause of GRAB breaking
(see HANDOFF.md's 2026-09-09 entry: a good-looking export missing LOGIN_INFO,
and yt-dlp's own cookie-jar save-back silently stripping it afterward).

Uses a PERSISTENT Playwright Chrome profile stored under
basiq_agent.DATA_DIR: a human logs into a dedicated Google account once
(--login, a real visible browser window), and after that this module can
refresh/re-validate that same session unattended and export it to a
Netscape-format cookies.txt -- the exact file COOKIES_FILE already points
yt-dlp at, and the exact format check_cookies.py already validates.

Usage:
    python youtube_session.py --login [cookies.txt]    one-time interactive
    python youtube_session.py --refresh [cookies.txt]  unattended refresh

Never run the --login step headless -- headless Chromium is the single most
detectable configuration there is. An unattended --refresh isn't guaranteed
to go unchallenged forever either; on any failure this leaves the existing
cookies.txt completely untouched rather than overwriting a known-good export
with a broken one. Per this project's standing rule, this module is only
ever exercised against real youtube.com by a human doing their own real
login (see --login) -- never by an automated test.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import basiq_agent

# PyInstaller doesn't (and can't) bundle a real Chrome binary into the onedir
# build -- `channel="chrome"` needs an actual `playwright install chrome`
# run once per machine (see tools/build/installer_worker.iss). Pointing this
# at DATA_DIR keeps that download alongside this app's other per-machine
# state (hf_cache, whisper_cache) instead of Playwright's own global default
# cache location, matching the self-contained, no-admin install model the
# rest of this app already follows.
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", str(basiq_agent.DATA_DIR / "ms-playwright"))

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sync_playwright = None  # type: ignore[assignment]

import check_cookies

PROFILE_DIR = basiq_agent.DATA_DIR / "youtube_profile"

_LOGIN_URL = "https://www.youtube.com/"
# A real video page, not the homepage -- check_cookies.py's docstring covers
# why that distinction is exactly what makes LOGIN_INFO show up or not.
_VALIDATE_URL = "https://www.youtube.com/watch?v=jNQXAC9IVRw"


def _netscape_line(cookie: dict) -> str:
    domain = cookie.get("domain", "")
    flag = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path") or "/"
    secure = "TRUE" if cookie.get("secure") else "FALSE"
    expires = cookie.get("expires")
    expiry = "0" if expires is None or expires < 0 else str(int(expires))
    return "\t".join([domain, flag, path, secure, expiry, cookie.get("name", ""), cookie.get("value", "")])


def export_cookies_netscape(cookies: list[dict], dest: Path) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by youtube_session.py -- do not edit by hand.",
        "",
    ]
    lines.extend(_netscape_line(c) for c in cookies)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_session(cookies_out: Path, *, force_interactive: bool = False,
                    headless: bool = True, timeout_s: float = 600) -> bool:
    """Refresh the persistent YouTube profile (or, if force_interactive, walk
    a human through logging into it for the first time), export cookies_out,
    and validate the export before trusting it.

    Returns True only if the export passes check_cookies.py's own validation.
    On any failure -- Playwright missing, browser launch failure, timed-out
    login, incomplete cookies -- returns False and leaves cookies_out
    completely untouched, so a bad refresh can never clobber a working file.
    """
    if sync_playwright is None:
        print("[youtube_session] playwright is not installed -- pip install playwright && playwright install chrome")
        return False

    PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    real_headless = False if force_interactive else headless

    try:
        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                user_data_dir=str(PROFILE_DIR),
                channel="chrome",
                headless=real_headless,
                args=["--mute-audio"],
            )
            try:
                page = context.pages[0] if context.pages else context.new_page()
                if force_interactive:
                    page.goto(_LOGIN_URL, timeout=30_000)
                    print(
                        "[youtube_session] Log into the dedicated Google account for "
                        "this identity in the window that just opened, then open any "
                        f"real YouTube video. Waiting up to {int(timeout_s)}s -- close "
                        "the window early to cancel."
                    )
                    deadline = time.time() + timeout_s
                    cookies = context.cookies()
                    while not any(c["name"] == "LOGIN_INFO" for c in cookies) and time.time() < deadline:
                        time.sleep(2)
                        cookies = context.cookies()
                else:
                    page.goto(_VALIDATE_URL, timeout=30_000)
                    page.wait_for_timeout(3000)
                    cookies = context.cookies()
            finally:
                context.close()
    except Exception as exc:
        print(f"[youtube_session] refresh failed, leaving {cookies_out} untouched: {exc}")
        return False

    tmp = cookies_out.with_suffix(cookies_out.suffix + ".refreshing")
    export_cookies_netscape(cookies, tmp)
    missing = check_cookies.missing_required(tmp)
    if missing:
        print(
            f"[youtube_session] refresh did not produce a valid session "
            f"(missing {', '.join(missing)}) -- keeping the existing {cookies_out}"
        )
        tmp.unlink(missing_ok=True)
        return False

    tmp.replace(cookies_out)
    print(f"[youtube_session] {cookies_out} refreshed and validated ({len(cookies)} cookies).")
    return True


def install_browser() -> bool:
    """Runs `playwright install chrome` for a machine that has no separate
    python.exe / pip-installed `playwright` CLI to invoke that with -- a
    frozen PyInstaller onedir build only ships this app's own exes, not a
    general-purpose Python. Uses Playwright's internal driver-invocation API
    (the same mechanism `python -m playwright install chrome` itself uses
    under the hood) since there's no public equivalent; not guaranteed
    stable across Playwright versions, and this is the first place to check
    if a future Playwright upgrade breaks browser installation in the
    frozen build.
    """
    try:
        from playwright._impl._driver import compute_driver_executable, get_driver_env
    except ImportError as exc:
        print(f"[youtube_session] could not import Playwright's driver internals: {exc}")
        return False

    import subprocess
    driver_executable, driver_cli = compute_driver_executable()
    result = subprocess.run(
        [str(driver_executable), str(driver_cli), "install", "chrome"],
        env=get_driver_env(),
    )
    return result.returncode == 0


def _cli() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("cookies_out", nargs="?", default="cookies.txt", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--login", action="store_true", help="one-time interactive login (visible browser)")
    mode.add_argument("--refresh", action="store_true", help="unattended refresh of an already-logged-in profile")
    mode.add_argument("--install-browser", action="store_true", help="run `playwright install chrome` (installer post-step)")
    args = parser.parse_args()

    if args.install_browser:
        sys.exit(0 if install_browser() else 1)

    ok = ensure_session(args.cookies_out, force_interactive=args.login, headless=True)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    _cli()
