/* =========================================================================
   archive_item_tags

   Mirrors public.tags (0004_tags.sql) one-for-one, for the archive side of
   the schema: same label/kind/source shape, generated by the same
   extract_tags() from tools/basiq_agent.py, just run directly against an
   archive item's existing transcript (tools/archive_consolidation/
   enrich_generate_tags.py) instead of through a fresh upload. auto tags stay
   disposable (re-tagging deletes and re-derives the whole auto set); manual
   is reserved for the same future use as it has on public.tags.

   Safe to run on an existing database; nothing here touches other tables.
   ========================================================================= */

create table if not exists public.archive_item_tags (
    id              uuid primary key default gen_random_uuid(),
    archive_item_id text not null references public.archive_items (id) on delete cascade,

    label           text not null check (char_length(trim(label)) between 1 and 60),
    source          text not null default 'auto' check (source in ('auto', 'manual')),
    /* What produced an auto tag: entity | topic | meta. Null for manual tags. */
    kind            text,

    created_at      timestamptz not null default now(),

    constraint archive_item_tags_unique_per_item unique (archive_item_id, label)
);

create index if not exists archive_item_tags_item_idx on public.archive_item_tags (archive_item_id);
create index if not exists archive_item_tags_label_idx on public.archive_item_tags (lower(label));

/* Deny-all, service-role bypasses - same posture as every other table here. */
alter table public.archive_item_tags enable row level security;
